export const locations = [
  "--Kowloon--",
  "Ho Man Tin",
  "Hung Hom",
  "Whampoa",
  "Kowloon City",
  "Kowloon Tong",
  "Kowloon Tsai",
  "To Kwa Wan",
  "Kwun Tong",
  "Lam Tin",
  "Ngau Tau Kok",
  "Jordan",
  "Kowloon Bay",
  "Yau Tong",
  "Sham Shui Po",
  "Cheung Sha Wan",
  "Lai Chi Kok",
  "Mei Foo",
  "Sham Shui Po",
  "Nam Cheong",
  "Shek Kip Mei",
  "Wong Tai Sin",
  "Diamond Hill",
  "Choi Hung",
  "San Po Kong",
  "Tsz Wan Shan",
  "Lok Fu",
  "Hung Hom",
  "Mong Kok",
  "Prince Edward",
  "Tai Kok Tsui",
  "Tsim Sha Tsui",
  "Yau Ma Tei",
  "--New Territories--",
  "Chek Lap Kok",
  "Cheung Chau",
  "Lamma Island",
  "Discovery Bay",
  "Mui Wo",
  "Ngong Ping",
  "Pui O",
  "Tai O",
  "Tung Chung",
  "Kwai Fong",
  "Kwai Hing",
  "Lai King",
  "Tai Wo Hau",
  "Tsing Yi",
  "Fanling",
  "Kwu Tung",
  "Lo Wu",
  "Sheung Shui",
  "Sai Kung",
  "Tseung Kwan O",
  "Hang Hau",
  "LOHAS Park",
  "Po Lam",
  "Tiu Keng Leng",
  "Sha Tin",
  "Fo Tan",
  "Kau To Shan",
  "Ma On Shan",
  "Heng On ",
  "Wu Kai Sha",
  "Che Kung Miu",
  "Sha Tin Wai",
  "Shek Mun",
  "Tai Wai",
  "Tai Po",
  "Tai Wo",
  "Tsuen Wan",
  "Tuen Mun",
  "Yuen Long",
  "--Hong Kong Island--",
  "Central",
  "Admiralty",
  "Mid-Levels",
  "SoHo",
  "Sai Wan",
  "Kennedy Town",
  "Sai Ying Pun",
  "Sheung Wan",
  "Chai Wan",
  "North Point",
  "Fortress Hill",
  "Quarry Bay",
  "Kornhill",
  "Taikoo Shing",
  "Sai Wan Ho",
  "Shau Kei Wan",
  "Aberdeen",
  "Ap Lei Chau",
  "Siu Sai Wan",
  "Cyberport",
  "Pok Fu Lam",
  "Victoria Peak",
  "Repulse Bay",
  "Stanley",
  "Shek O",
  "Wong Chuk Hang",
  "Causeway Bay",
  "Tin Hau",
  "Wan Chai",
];

export const types = [
  "Restaurant",
  "Shopping",
  "Health and Beauty",
  "Grocery",
  "other",
];
